import { getSpacing } from './helpers';

export const light = {
  name: 'light',
  breakpoints: {
    xs: 0,
    sm: 600,
    md: 960,
    lg: 1280,
    xl: 1920,
  },
  palette: {
    primary: {
      dark: '#b28704',
      main: '#ffc107',
      light: '#ffcd38',
    },
    secondary: {
      dark: '#ab003c',
      main: '#f50057',
      light: '#f73378',
    },
    background: {
      default: '#FFFFFF',
      dark: '#CECECE',
    },
    border: {
      default: '#3E3E3E',
      dark: '#000000',
    },
    common: {
      white: '#FFFFFF',
      black: '#000000',
    },
  },
  typography: {
    h1: {
      fontFamily: 'Roboto, sans-serif',
      fontWeight: 500,
      fontSize: '96px',
      lineHeight: '112px',
      color: 'rgba(0,0,0,0.87)',
      letterSpacing: '-1.5px',
    },
    h2: {
      fontFamily: 'Roboto, sans-serif',
      fontWeight: 500,
      fontSize: '60px',
      lineHeight: '70px',
      color: 'rgba(0,0,0,0.87)',
      letterSpacing: '-0.5px',
    },
    h3: {
      fontFamily: 'Roboto, sans-serif',
      fontWeight: 'normal',
      fontSize: '48px',
      lineHeight: '56px',
      color: 'rgba(0,0,0,0.87)',
    },
    h4: {
      fontFamily: 'Roboto, sans-serif',
      fontWeight: 'normal',
      fontSize: '36px',
      lineHeight: '42px',
      color: 'rgba(0,0,0,0.87)',
      letterSpacing: '0.25px',
    },
    h5: {
      fontFamily: 'Roboto, sans-serif',
      fontWeight: 400,
      fontSize: '28px',
      lineHeight: '32px',
      color: 'rgba(0,0,0,0.87)',
    },
    h6: {
      fontFamily: 'Roboto, sans-serif',
      fontWeight: 500,
      fontSize: '24px',
      lineHeight: '24px',
      color: 'rgba(0,0,0,0.87)',
      letterSpacing: '0.15px',
    },
    body1: {
      fontFamily: 'Roboto, sans-serif',
      fontWeight: 'normal',
      fontSize: '20px',
      lineHeight: '28px',
      color: 'rgba(0,0,0,0.6)',
      letterSpacing: '0.5px',
    },
    body2: {
      fontFamily: 'Roboto, sans-serif',
      fontWeight: 400,
      fontSize: '18px',
      lineHeight: '20px',
      color: 'rgba(0,0,0,0.6)',
      letterSpacing: '0.25px',
    },
    subtitle1: {
      fontFamily: 'Roboto, sans-serif',
      fontWeight: 'normal',
      fontSize: '20px',
      lineHeight: '24px',
      color: 'rgba(0,0,0,0.6)',
      letterSpacing: '0.15px',
    },
    subtitle2: {
      fontFamily: 'Roboto, sans-serif',
      fontWeight: 500,
      fontSize: '18px',
      lineHeight: '24px',
      color: 'rgba(0,0,0,0.6)',
      letterSpacing: '0.25px',
    },
    button: {
      fontFamily: 'Roboto, sans-serif',
      fontWeight: 500,
      fontSize: '16px',
      lineHeight: '16px',
      color: 'rgba(0,0,0,0.87)',
      letterSpacing: '0.75px',
    },
    caption: {
      fontFamily: 'Roboto, sans-serif',
      fontWeight: 'normal',
      fontSize: '14px',
      lineHeight: '16px',
      color: 'rgba(0,0,0,0.6)',
      letterSpacing: '0.4px',
    },
    overline: {
      fontFamily: 'Roboto, sans-serif',
      fontWeight: 500,
      fontSize: '14px',
      lineHeight: '16px',
      color: 'rgba(0,0,0,0.6)',
      textTransform: 'initial',
    },
  },
  spacing: getSpacing,
};

export type TAppTheme = typeof light;
